### ISSUE TITLE
tabix 

### ISSUE THREAD

**Issue by wbranicki** [xihaoli/MACIE#1]
Dear Dr Li, 

I was trying to start using the scoring from MACIE and after using the suggested comand I received this information in return:

The index file is older than the data file: MACIE_hg19_noncoding_chr4.tab.bgz.tbi

Another question: is it possible to easily use MACIE scores when a genome was mapped using newer version of the ref sequence?

Thank you. 
Best, 
Wojciech

**Comment by xihaoli** [comment]
Hi Wojciech,

Thank you for your questions. I just checked the data file locally, and I can successfully run the command for chromosome 4 without any issues. My `htslib` version is `1.14`, could you please check your software version?

Yes, you can map the newer version of the ref sequence to hg19 via a liftOver and use MACIE scores.

Best,
Xihao

**Comment by wbranicki** [comment]
Hello Xihao,

thank you for the response. My version is 1.11 but meanwhile it turned out that the index file must be uploaded after the main file and the problem has been solved. After uploading the idex file with a more recent date than the data file, it is working perfectly. Thank you!
We will use lift Over.
Best wishes,
Wojciech
________________________________

**Comment by xihaoli** [comment]
You are very welcome, Wojciech! Glad to hear the problem has been solved. Feel free to let me know if you have any questions and happy to help.
Best,
Xihao
